### ISSUE TITLE
Please make life simpler for everybody using the maproulette API (Question wrt client authentication)

### ISSUE THREAD

**Issue by simonpoole** [maproulette/maproulette-backend#476]
It is not quite clear from the API doc what the intended model for a third party client app to obtain an api-key is. 

Simply require the user to C&P from the MR UI, or is there a way to authenticate via the API so that the apikey can be retrieved?

**Comment by mgcuthbert** [comment]
At this moment there is no way to authenticate via the API apart from using the API key. So the key would need to be generated by the user and then retrieved through the API. 

So in a 3rd party client app, you would need to have some sort of settings field allowing a user of the app to insert their API key which then be able to make the requests.

**Comment by simonpoole** [comment]
@mgcuthbert thanks for the response. I was already suspecting so much. 

A real simple solution for this would for maproulette to store the api key in the users OSM preferences when (re-) generated. This would allow other authorised apps to retrieve the key (in a secure fashion) without requiring the user to C&P on mobile. If the user removes the apps authorisation it then has no access to the apikey either, which potentially be an issue if the key is stored locally.

**Comment by matkoniecz** [comment]
At this moment using Maproulette in Vespucci works as follows:

- users solves task
- uploads changes
- get "enter Maproulette API key field", what is horrible for any user who is not a programmer/has experience with technical side of APIs. What covers >99% of OSM mappers and even for others this is obnoxious UX.

As I understand there is no way to improve this in Vespucci, except disabling Maproulette by default.

**Comment by simonpoole** [comment]
@matkoniecz just as a note, what the use has to do is spelt out in no unclear terms in http://vespucci.io/help/en/12.0.0%20Release%20notes/#support-for-maproulette

**Comment by matkoniecz** [comment]
The tricky part is that users generally are not reading release notes.

Especially ones that will start using Vespucci in future rather than upgrading from the old version.

**Comment by mvexel** [comment]
> A real simple solution for this would for maproulette to store the api key in the users OSM preferences when (re-) generated.

This seems to make sense but would [require an authenticated OSM API call](https://wiki.openstreetmap.org/wiki/API_v0.6#Preferences_of_the_logged-in_user). This should be possible since we already have an OSM API token for the user, but I don't think we currently ask for preferences write permissions when the user authenticates with OSM. This can of course be changed.

**Comment by simonpoole** [comment]
Alternatively, but not as user friendly, would be to at least add a button that would copy the key in to the C&P buffer of the system in question. Still is a multi/many step operation but at least not so error prone as trying to copy the key manually.

**Comment by mvexel** [comment]
I opened a separate ticket in the maproulette3 repo to specifically cover the API key enhancement, since this would need to be implemented in the front end: https://github.com/osmlab/maproulette3/issues/1745. 

As I mention there, my remaining concern is that there is no granular control over OSM user prefs read permissions, which could lead to unintended consequences for the user. Any application with read permissions on the user's OSM preferences could grab the key and make authenticated calls to the MapRoulette API. While reading OSM user preferences would of course require explicit consent of the user, you could argue that the user does not really know what they are 'giving away'. If all kinds of applications start storing API keys in there, granting OSM user preference read permissions really means granting restricted API access to all those applications. Is my understanding here correct?

**Comment by simonpoole** [comment]
Your understanding is correct and there is actually a longer issue thread on the rail-ports issue tracker on the subject. But even in that discussion nobody was suggesting fine grained access to prefs, it was more all or nothing on a per app base.

There are naturally other ways to fix this, they will simply all be a bit hackish.

**Comment by mvexel** [comment]
Right. I don't see this as a huge vulnerability right now, since granting OSM user preferences read permissions is probably something a fairly small amount of people do, and those people are likely to be pretty savvy about this anyway. But it would be nice to have a link in the OAuth permissions screen to a human-readable presentation of the contents of your preferences so users can make an educated guess.

**Comment by mmd-osm** [comment]
> there is actually a longer issue thread on the rail-ports issue tracker on the subject. 

The issue wasn't really that long: https://github.com/openstreetmap/openstreetmap-website/issues/2326

I closed it after a year because it wasn't going anywhere.

**Comment by mvexel** [comment]
This was resolved in [#1745 ](https://github.com/maproulette/maproulette3/issues/1745) by way of https://github.com/maproulette/maproulette-backend/pull/990

**Comment by mvexel** [comment]
The API key is stored in the maproulette_apikey_v2 key in the OSM user preferences (api/0.6/user/preferences)
